### ISSUE TITLE
Deadlock on sigint when multiple rmw impl's available

### ISSUE THREAD

**Issue by dhood** [ros2/rmw_implementation#25]
**Context**
There's a race condition in handling a sigint that only occurs when multiple rmw implementations are supported.

In our test suite it manifests as a timeout when test executables have the correct output and shutdown is triggered by launch_testing, but they don't respond to the sigint correctly, e.g. http://ci.ros2.org/view/nightly/job/nightly_osx_repeated/769/testReport/junit/(root)/projectroot/test_tutorial_list_parameters__rmw_fastrtps_cpp/

You'll see from this job that if only one rmw implementation is available (rmw_fastrtps_cpp in this case), the test can pass fine 150 times: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2942)](http://ci.ros2.org/view/All/job/ci_linux/2942/)

**Cause**
I think this would have started occurring since https://github.com/ros2/launch/pull/44

I've traced it to this line:
https://github.com/ros2/rmw_implementation/blob/f6288c83a7446017a39dd18332e658a46eb66bcc/rmw_implementation/src/functions.cpp#L148, trying to call `rmw_trigger_guard_condition` in the underlying rmw implementation, but `hasSymbol` never gets called in poco underneath.

I think the problem is that the `lib` variable is static and is being destroyed on shutdown too early. I'm not yet an expert in the workings of rmw_implementation/memory management so if someone could confirm that that "make sense" that would be appreciated.

**Fix**
If that's a reasonable cause, is an appropriate fix to make the `lib` variable not static? Or does it need to be static because of particular implementation details and we should instead implement a workaround to prevent it from being used after destructed?

**Comment by dhood** [comment]
by the way, at first I thought that poco had some signal handler that was being triggered in parallel, but none of the methods in https://github.com/pocoproject/poco/blob/dcdcee5afab6e8972f1b144ef7e7e884f85e83a3/Foundation/src/SignalHandler.cpp get called at any point in the test executables so I've ruled it out.

**Comment by dirk-thomas** [comment]
I am not sure if it is possible that the static variable is already being destroyed while the code is still "running" and trying to call symbols. To clarify if that is actually the case I would suggest to add some debug output when the static variable is being destroyed.

**Comment by dhood** [comment]
you were right that that wasn't the issue, thanks. the place where it's actually getting stuck is [poco trying to lock a mutex inside `hasSymbol`](https://github.com/pocoproject/poco/blob/dd30db6ca9b05c8e5984b35f012ca3ed534913d6/Foundation/src/SharedLibrary_UNIX.cpp#L85)

from what I can tell, the process is interrupted during the destructor of the lock in another function call, then when the lock is needed for the cleanup of the signal handling it waits for it forever.

@dirk-thomas and I spoke offline and think it's because that process will naturally exit after it's printed parameters. The sigint from launch_testing must be interrupting the "natural" teardown when the process exits. If that interruption occurs while poco has a scoped lock on the sharedlibrary that it can't release, this causes the deadlock.

This job tests all of the `*_parameters_*` demo executables multiple times, both rmw implementations in use. However, it includes [the addition of sleeps for those demos](https://github.com/ros2/demos/commit/96e8d9ab3f77e46e376a936bca1c90f2f018bd90) so that launch_testing will not interrupt a shutdown: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2951)](http://ci.ros2.org/view/All/job/ci_linux/2951/) It got through the 8 tests 41 times without deadlock, and on the 42nd something happened at [startup that looks to be cause by something unrelated](http://ci.ros2.org/view/All/job/ci_linux/2951/testReport/(root)/projectroot/test_tutorial_set_and_get_parameters__rmw_fastrtps_cpp/). 41 successful tests to me shows that the issue of deadlock at sigint is probably caused by the double-shutdown.

I'll attempt the following moving forward:
1. get rclcpp to ignore sigints while shutting down to prevent a deadlock.
1. if necessary, add a sleep to the demos to ensure that launch_testing is the one that's shutting the process down, not them naturally exiting (but I don't think this will be needed to make the tests pass).

**Comment by dirk-thomas** [comment]
I might want to call `rclcpp::utilities::shutdown()` before the `main` returns. If that is not sufficient I would suggest to register the removal of the signal handler in the `init()` function so that is gets restored to the original state during shutdown.
