### ISSUE TITLE
error from library loader is not as helpful as it could be

### ISSUE THREAD

**Issue by BrannonKing** [ros2/rmw_implementation#33]
When I fail to have the CoreDX environment established, I get an error about being unable to load a library. Unfortunately, the error does not specify the library that failed to load (and it's typically a library several layers deep that failed to load). Please modify the code to look more like this: 
```cpp
    if (library_path.empty()) {
      RMW_SET_ERROR_MSG(("failed to find shared library of rmw implementation. Searched " + env_var).c_str());
      return nullptr;
    }
    try {
      lib = new Poco::SharedLibrary(library_path);
    } catch (Poco::LibraryLoadException& e) {
      RMW_SET_ERROR_MSG(("failed to load shared library of rmw implementation. Exception: " + e.displayText()).c_str());
      return nullptr;
    } catch (...) {
      RMW_SET_ERROR_MSG(("failed to load shared library of rmw implementation: " + library_path).c_str());
      return nullptr;
    }
```

Also note that the library-load code is duplicated in rosidl_typesupport.

**Comment by dirk-thomas** [comment]
This looks like a good improvement. I would be great if you could provide a pull request with the proposed patch. That will likely speed up the time until this enhancement is available.

**Comment by kunaltyagi** [comment]
Somehow the PR got closed. GH says the code is not different... but GH is wrong.

**Comment by dirk-thomas** [comment]
@kunaltyagi: @mikaelarguedas asked you on the PR (https://github.com/ros2/rmw_implementation/pull/35#issuecomment-351813737) if you still have the code somewhere / and if yes, are you still planning to open a PR with that improvement.

**Comment by BrannonKing** [comment]
I never did have a pull request for this ready; I made the change on my local system when testing but never checked it in. I guess I was hoping that we could eliminate the duplicate code; I wasn't sure where to push the change or if I should do it in both places.

**Comment by dhood** [comment]
@kunaltyagi if you or anyone else can open another PR with https://github.com/kunaltyagi/rmw_implementation/commit/661746da0d0d662dbe6aff7144fce27c015b4bc0 and address the comments from https://github.com/ros2/rmw_implementation/pull/35 we can continue iterating.

**Comment by dirk-thomas** [comment]
I created #37 based on the visible diff (since the commit hash is not available anymore) and made it pass the linters.
