### ISSUE TITLE
/home/pedestrian/ros2_java_ws/src/ros2/rmw_implementation/rmw_implementation/src/functions.cpp

### ISSUE THREAD

**Issue by Pedestrian1671022** [ros2/rmw_implementation#38]
/home/pedestrian/ros2_java_ws/src/ros2/rmw_implementation/rmw_implementation/src/functions.cpp:367:16: error: ‘rmw_log_severity_t’ was not declared in this scope
   1, ARG_TYPES(rmw_log_severity_t))
                ^
/home/pedestrian/ros2_java_ws/src/ros2/rmw_implementation/rmw_implementation/src/functions.cpp:176:19: note: in definition of macro ‘EXPAND’
 #define EXPAND(x) x
                   ^
/home/pedestrian/ros2_java_ws/src/ros2/rmw_implementation/rmw_implementation/src/functions.cpp:212:26: note: in expansion of macro ‘ARGS_1’
   ReturnType name(EXPAND(ARGS_ ## _NR(__VA_ARGS__))) \
                          ^
/home/pedestrian/ros2_java_ws/src/ros2/rmw_implementation/rmw_implementation/src/functions.cpp:365:1: note: in expansion of macro ‘RMW_INTERFACE_FN’
 RMW_INTERFACE_FN(rmw_set_log_severity,
 ^
/home/pedestrian/ros2_java_ws/src/ros2/rmw_implementation/rmw_implementation/src/functions.cpp:367:6: note: in expansion of macro ‘ARG_TYPES’
   1, ARG_TYPES(rmw_log_severity_t))
      ^
/home/pedestrian/ros2_java_ws/src/ros2/rmw_implementation/rmw_implementation/src/functions.cpp:213:3: error: expected ‘,’ or ‘;’ before ‘{’ token
   { \
   ^
/home/pedestrian/ros2_java_ws/src/ros2/rmw_implementation/rmw_implementation/src/functions.cpp:365:1: note: in expansion of macro ‘RMW_INTERFACE_FN’
 RMW_INTERFACE_FN(rmw_set_log_severity,
 ^
/home/pedestrian/ros2_java_ws/src/ros2/rmw_implementation/rmw_implementation/src/functions.cpp:421:1: error: expected ‘}’ at end of input
 }
 ^
CMakeFiles/rmw_implementation.dir/build.make:62: recipe for target 'CMakeFiles/rmw_implementation.dir/src/functions.cpp.o' failed
make[2]: *** [CMakeFiles/rmw_implementation.dir/src/functions.cpp.o] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/rmw_implementation.dir/all' failed
make[1]: *** [CMakeFiles/rmw_implementation.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

<== Command '. /home/pedestrian/ros2_java_ws/build_isolated/rmw_implementation/cmake__build.sh && /usr/bin/make -j8 -l8' failed in '/home/pedestrian/ros2_java_ws/build_isolated/rmw_implementation' with exit code '2'
<== Command '. /home/pedestrian/ros2_java_ws/build_isolated/rmw_implementation/cmake__build.sh && /usr/bin/make -j8 -l8' failed in '/home/pedestrian/ros2_java_ws/build_isolated/rmw_implementation' with exit code '2'

**Comment by mikaelarguedas** [comment]
@Pedestrian1671022 there is not enough information in the description. Please fill out the issue template when submitting an issue. Formatting the code and console output is also appreciated.
We encourage you to ask debugging question on [ROS Answers](https://answers.ros.org/questions/) and open issues on Github only when confirmed that there is a bug in the code.

If I had to guess I'd say that you are building custom packages using the latest API from `master` but using `ardent` packages for your dependencies. The [addition of `rmw_log_severity_t`](https://github.com/ros2/rmw/pull/124) happened **after** the Ardent release so is not part of the binary packages.

You can either try to build from source or use the `ardent` branch of the repositories you are modifying the sources.

I'm closing this, feel free to post a new question on [ROS answers](https://answers.ros.org/questions/) following our [support guidelines](http://wiki.ros.org/Support) if you still face problems compiling
