### ISSUE TITLE
Build fails if the same RMW implementation appears multiple times in the AMENT_PREFIX_PATH

### ISSUE THREAD

**Issue by gerkey** [ros2/rmw_implementation#4]
If you have a multi-element `AMENT_PREFIX_PATH` that contains the same RMW implementation twice, then you can get an error like this:

````
CMake Error at /Users/gerkey/ros2_ws/install/share/rmw_implementation/cmake/add_executable_for_each_rmw_implementation.cmake:66 (add_executable):
  add_executable cannot create target "intrapc__rmw_opensplice_cpp" because
  another target with the same name already exists.  The existing target is
  an executable created in source directory
  "/Users/gerkey/ros2_ws/src/ros2/demos/intra_process_comms".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  CMakeLists.txt:21 (add_executable_for_each_rmw_implementations)
````
I confirmed that [`get_available_rmw_implementations()`](https://github.com/ros2/rmw_implementation/blob/master/rmw_implementation/cmake/add_executable_for_each_rmw_implementation.cmake#L45) was returning a list with duplicates: `rmw_opensplice_cpp;rmw_opensplice_cpp`.

In this case, my `AMENT_PREFIX_PATH` was:
````
AMENT_PREFIX_PATH=/Users/gerkey/ros2_ws/install:/Users/gerkey/ros2_install/ros2
````
I had previously sourced the setup file for a binary install (the `ros2_install` element).  I had also sourced the setup file from install tree where I was building, but that shouldn't be a problem.

Now, perhaps I'm in the wrong for getting into this configuration, but it would be good to fix, or at least get a better error message.

I'm inclined to `REMOVE_DUPLICATES` inside `get_available_rmw_implementations()`, but am open to other options.

**Comment by dirk-thomas** [comment]
Can you please double check that the following branch of ament_cmake fixes the problem for you: https://github.com/ament/ament_cmake/tree/duplicate_resources

**Comment by gerkey** [comment]
Confirmed, that fixes it, thanks!
