### ISSUE TITLE
cmake: Still build with shared lib loading support, even if there's only one?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [ros2/rmw_implementation#58]
At present, the current `CMakeLists.txt` seems a bit too implicit:
https://github.com/ros2/rmw_implementation/blob/c5f5324/rmw_implementation/CMakeLists.txt#L41-L44

Can this be made into an explicit CMake switch, something like `-DFORWARD_RMW_IMPLEMENTATION={OFF,ON}`?

Rationale:
I'm developing on a machine that only has one RMW implementation present.
In debugging stuff like https://github.com/ros2/rcpputils/issues/3 and https://github.com/ros2/rcutils/issues/143, it I couldn't just rebuild `rmw_implementation` to reproduce what I have installed as a binary.

The only way that I can reproduce the binary is either (a) modify `CMakeLists.txt` or (b) install an (unused) RMW implementation, which is odd... ([example patch line](https://github.com/EricCousineau-TRI/repro/commit/cea11026722b340580257564dc49cb0f59b55178#diff-19a9c16469e9b7649ce20f547b993418R12))

I should be able reproduce this with my installed packages?

**Comment by dirk-thomas** [comment]
> Can this be made into an explicit CMake switch ...?

That sounds fine. I would suggest adding a boolean CMake option like `RMW_IMPLEMENTATION_FORCE_POCO`. Please consider creating a pull request for this.
